stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the project..."
    # edited 2eme

test:
  stage: test
  script:
    - echo "Running tests..."

deploy_staging:
  stage: deploy
  script:
    - echo "Deploying to staging environment..."

